import type { DecideResponse } from '~backend/cards/decide';
import type { ChatResponse } from '~backend/ai/chat';
import type { CardProfileResponse } from '~backend/cards/profile';

/**
 * Thin typed access to the decision engine.
 *
 * client.ts is generated by `encore gen client` and gets overwritten on every
 * backend sync, so the new endpoints live here instead. Types are imported
 * straight from the backend source, so this stays honest without codegen.
 */

const BASE = (import.meta.env.VITE_CLIENT_TARGET as string) || 'http://localhost:4000';

export type { DecideResponse };
export type Decision = DecideResponse;

async function getJSON<T>(path: string, params: Record<string, string | number | undefined>): Promise<T> {
  const q = new URLSearchParams();
  for (const [k, v] of Object.entries(params)) {
    if (v !== undefined && v !== null && v !== '') q.set(k, String(v));
  }
  const res = await fetch(`${BASE}${path}?${q.toString()}`, { credentials: 'include' });
  if (!res.ok) throw new Error(`${path} responded ${res.status}`);
  return (await res.json()) as T;
}

/** Deterministic. No model involved, so this is the fast path. */
export function decide(userId: string, category: string, amountCents?: number) {
  return getJSON<DecideResponse>('/cards/decide', { userId, category, amountCents });
}

/** Same decision, phrased by the model, with the deterministic sentence as fallback. */
export async function ask(userId: string, message: string, amountCents?: number) {
  const res = await fetch(`${BASE}/ai/chat`, {
    method: 'POST',
    credentials: 'include',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ userId, message, amountCents }),
  });
  if (!res.ok) throw new Error(`/ai/chat responded ${res.status}`);
  return (await res.json()) as ChatResponse;
}

/** Everything about one card: rates, caps left, benefits used, live offers. */
export function cardProfile(userId: string, cardId: number) {
  return getJSON<CardProfileResponse>('/cards/profile', { userId, cardId });
}

export type { CardProfileResponse };
export type CardProfile = CardProfileResponse;

// ---------------------------------------------------------------------------
// Offers by forwarded email
// ---------------------------------------------------------------------------

export interface OfferInbox {
  address: string;
  receivedCount: number;
  lastReceivedAt?: string;
  recent: {
    id: number;
    issuer?: string;
    subject?: string;
    offersFound: number;
    offersWritten: number;
    status: string;
    createdAt: string;
  }[];
}

export interface PendingOffer {
  id: number;
  merchantName: string;
  offerDescription: string;
  issuer?: string;
  lastFour?: string;
  endDate?: string;
}

/** The user's forwarding address, created on first ask. */
export function offerInbox(userId: string) {
  return getJSON<OfferInbox>('/offers/inbox', { userId });
}

/** Offers we held because we could not tell which card they belong to. */
export function pendingOffers(userId: string) {
  return getJSON<{ offers: PendingOffer[] }>('/offers/pending', { userId });
}

async function postJSON<T>(path: string, body: unknown): Promise<T> {
  const res = await fetch(`${BASE}${path}`, {
    method: 'POST',
    credentials: 'include',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
  });
  if (!res.ok) throw new Error(`${path} responded ${res.status}`);
  return (await res.json()) as T;
}

/** Place a held offer on a card. Teaches the card's last four for next time. */
export function attributeOffer(userId: string, offerId: number, cardId: number) {
  return postJSON<{ ok: boolean }>('/offers/attribute', { userId, offerId, cardId });
}

export interface CardIdentity {
  lastFour?: string;
  cardEmail?: string;
  address?: string;
}

/**
 * Teach the app to recognise one card in forwarded mail. Last four is read
 * straight out of most issuer offer mail; the registered mailbox survives
 * forwarding in the headers; a dedicated address removes the guessing entirely.
 */
export function setCardIdentity(input: {
  userId: string;
  cardId: number;
  lastFour?: string;
  cardEmail?: string;
  wantOwnAddress?: boolean;
}) {
  return postJSON<CardIdentity>('/offers/card-identity', input);
}

export function rotateOfferInbox(userId: string) {
  return postJSON<{ address: string }>('/offers/inbox/rotate', { userId });
}

export function formatMoney(cents: number): string {
  return '$' + (cents / 100).toFixed(cents % 100 === 0 ? 0 : 2);
}
