import type { DecideResponse } from '~backend/cards/decide';
import type { ChatResponse } from '~backend/ai/chat';
import type { CardProfileResponse } from '~backend/cards/profile';

/**
 * Thin typed access to the decision engine.
 *
 * client.ts is generated by `encore gen client` and gets overwritten on every
 * backend sync, so the new endpoints live here instead. Types are imported
 * straight from the backend source, so this stays honest without codegen.
 */

const BASE = (import.meta.env.VITE_CLIENT_TARGET as string) || 'http://localhost:4000';

export type { DecideResponse };
export type Decision = DecideResponse;

async function getJSON<T>(path: string, params: Record<string, string | number | undefined>): Promise<T> {
  const q = new URLSearchParams();
  for (const [k, v] of Object.entries(params)) {
    if (v !== undefined && v !== null && v !== '') q.set(k, String(v));
  }
  const res = await fetch(`${BASE}${path}?${q.toString()}`, { credentials: 'include' });
  if (!res.ok) throw new Error(`${path} responded ${res.status}`);
  return (await res.json()) as T;
}

/** Deterministic. No model involved, so this is the fast path. */
export function decide(userId: string, category: string, amountCents?: number) {
  return getJSON<DecideResponse>('/cards/decide', { userId, category, amountCents });
}

/** Same decision, phrased by the model, with the deterministic sentence as fallback. */
export async function ask(userId: string, message: string, amountCents?: number) {
  const res = await fetch(`${BASE}/ai/chat`, {
    method: 'POST',
    credentials: 'include',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ userId, message, amountCents }),
  });
  if (!res.ok) throw new Error(`/ai/chat responded ${res.status}`);
  return (await res.json()) as ChatResponse;
}

/** Everything about one card: rates, caps left, benefits used, live offers. */
export function cardProfile(userId: string, cardId: number) {
  return getJSON<CardProfileResponse>('/cards/profile', { userId, cardId });
}

export type { CardProfileResponse };
export type CardProfile = CardProfileResponse;

export function formatMoney(cents: number): string {
  return '$' + (cents / 100).toFixed(cents % 100 === 0 ? 0 : 2);
}
